import type { LyricToken } from './types'

export const lyricTokens: LyricToken[] = [
  { character: '我', jyutping: 'ngo' },
  { character: '終', jyutping: 'zung' },
  { character: '身', jyutping: 'san' },
  { character: '志', jyutping: 'zi' },
  { character: '願', jyutping: 'jyun' },
  { character: '，', jyutping: '', isPunctuation: true },
  { character: '為', jyutping: 'wai' },
  { character: '所', jyutping: 'so' },
  { character: '愛', jyutping: 'oi' },
  { character: '認', jyutping: 'jing' },
  { character: '命', jyutping: 'ming' },
  { character: '，', jyutping: '', isPunctuation: true },
  { character: '或', jyutping: 'waak' },
  { character: '為', jyutping: 'wai' },
  { character: '所', jyutping: 'so' },
  { character: '信', jyutping: 'seon' },
  { character: '分', jyutping: 'fan' },
  { character: '開', jyutping: 'hoi' },
  { character: '，', jyutping: '', isPunctuation: true },
  { character: '如', jyutping: 'jyu' },
  { character: '沒', jyutping: 'mut' },
  { character: '法', jyutping: 'faat' },
  { character: '可', jyutping: 'ho' },
  { character: '兼', jyutping: 'gim' },
  { character: '有', jyutping: 'jau' },
]
