import type { LyricToken } from './types'

export const lyricTokens: LyricToken[] = [
  { character: '忘', jyutping: 'mong' },
  { character: '掉', jyutping: 'diu' },
  { character: '种', jyutping: 'zung' },
  { character: '过', jyutping: 'gwo' },
  { character: '的', jyutping: 'dik' },
  { character: '花', jyutping: 'faa' },
  { character: ' ', jyutping: '', isPunctuation: true },
  { character: '重', jyutping: 'cung' },
  { character: '新', jyutping: 'san' },
  { character: '的', jyutping: 'dik' },
  { character: '出', jyutping: 'ceot' },
  { character: '发', jyutping: 'faat' },
  { character: ' ', jyutping: '', isPunctuation: true },
  { character: '放', jyutping: 'fong' },
  { character: '弃', jyutping: 'hei' },
  { character: '理', jyutping: 'lei' },
  { character: '想', jyutping: 'soeng' },
  { character: '吧', jyutping: 'baa' },
  { character: '就', jyutping: 'zau' },
  { character: '似', jyutping: 'ci' },
  { character: '这', jyutping: 'ze' },
  { character: '一', jyutping: 'jat' },
  { character: '区', jyutping: 'keoi' },
  { character: ' ', jyutping: '', isPunctuation: true },
  { character: '曾', jyutping: 'cang' },
  { character: '经', jyutping: 'ging' },
  { character: '称', jyutping: 'cing' },
  { character: '得', jyutping: 'dak' },
  { character: '上', jyutping: 'soeng' },
  { character: ' ', jyutping: '', isPunctuation: true },
  { character: '美', jyutping: 'mei' },
  { character: '满', jyutping: 'mun' },
  { character: '甲', jyutping: 'gaap' },
  { character: '天', jyutping: 'tin' },
  { character: '下', jyutping: 'haa' },
  { character: '忘', jyutping: 'mong' },
  { character: '掉', jyutping: 'diu' },
  { character: '爱', jyutping: 'oi' },
  { character: '过', jyutping: 'gwo' },
  { character: '的', jyutping: 'dik' },
  { character: '他', jyutping: 'taa' },
  { character: '忘', jyutping: 'mong' },
  { character: '掉', jyutping: 'diu' },
  { character: '砌', jyutping: 'cai' },
  { character: '过', jyutping: 'gwo' },
  { character: '的', jyutping: 'dik' },
  { character: '沙', jyutping: 'saa' },
  { character: ' ', jyutping: '', isPunctuation: true },
  { character: '回', jyutping: 'wui' },
  { character: '忆', jyutping: 'jik' },
  { character: '的', jyutping: 'dik' },
  { character: '堡', jyutping: 'bou' },
  { character: '垒', jyutping: 'leoi' },
  { character: ' ', jyutping: '', isPunctuation: true },
  { character: '刹', jyutping: 'caat' },
  { character: '那', jyutping: 'naa' },
  { character: '已', jyutping: 'ji' },
  { character: '倒', jyutping: 'dou' },
  { character: '下', jyutping: 'haa' },
  { character: '忘', jyutping: 'mong' },
  { character: '掉', jyutping: 'diu' },
  { character: '爱', jyutping: 'oi' },
  { character: '过', jyutping: 'gwo' },
  { character: '的', jyutping: 'dik' },
  { character: '他', jyutping: 'taa' },
  { character: '请', jyutping: 'cing' },
  { character: '放', jyutping: 'fong' },
  { character: '下', jyutping: 'haa' },
  { character: '手', jyutping: 'sau' },
  { character: '里', jyutping: 'leoi' },
  { character: '那', jyutping: 'naa' },
  { character: '锁', jyutping: 'so' },
  { character: '匙', jyutping: 'ci' },
  { character: ' ', jyutping: '', isPunctuation: true },
  { character: '好', jyutping: 'hou' },
  { character: '吗', jyutping: 'maa' }
]
